### PR TITLE
Update @SourceStreams and @SinkStreams docs to clarify that they are required

### PR DESCRIPTION
**Pull request by nicoweidner**
Resolves https://github.com/decodableco/decodable-pipeline-sdk/issues/45

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM. One additional thing we could do is raising a warning in the [annotation processor](https://github.com/decodableco/decodable-pipeline-sdk/blob/main/sdk/src/main/java/co/decodable/sdk/pipeline/internal/metadata/MetadataProcessor.java) which creates the META-INF file if there are no streams at all. While it's technically still valid (if a user doesn't want to connect to any Decodable streams at all), I think it should be the exceptional case. So more users would benefit from that build-time warning than would be irritated by a "false" warning. WDYT?

**Review by gunnarmorling — APPROVED** [review]

**Comment by nicoweidner** [comment]
> LGTM. One additional thing we could do is raising a warning in the [annotation processor](https://github.com/decodableco/decodable-pipeline-sdk/blob/main/sdk/src/main/java/co/decodable/sdk/pipeline/internal/metadata/MetadataProcessor.java) which creates the META-INF file if there are no streams at all. While it's technically still valid (if a user doesn't want to connect to any Decodable streams at all), I think it should be the exceptional case. So more users would benefit from that build-time warning than would be irritated by a "false" warning. WDYT?

Ok, I tried to change the processor so it always runs and prints a warning when neither sources nor sinks are specified. It now processes all annotations so that it's not skipped entirely if the annotations are not present - but in turn, it doesn't mark the annotations as processed so other processors can process their annotations afterwards.

I also fixed a NPE I noticed by chance.

**Comment by nicoweidner** [comment]
@gunnarmorling quick ping

**Review by gunnarmorling — APPROVED** [review]
LGTM, thx!

**Pull request merged**
