### PR TITLE
#76: Making sure example builds with Java 22+

### LINKED ISSUE #76: Update Maven buid config of example to work with Java 23+
As of Java ~~22~~ 23, annotation processing must be [explicitly enabled](https://inside.java/2024/06/18/quality-heads-up/) (the change was moved from Java 22 to 23) when building a project. I.e. it is not sufficient any longer to solely provide a JAR with a processor on the classpath.

### PR DESCRIPTION
**Pull request by gunnarmorling**
Fixes #76.

### CODE REVIEW

**Comment by nicoweidner** [comment]
I ran:
```
$ sdk use java 21.0.4-amzn
decodable-pipeline-sdk/examples/custom-pipelines-hello-world$ ./mvnw clean package
```
Same thing with `$ sdk use java 22.0.2-amzn` and `$ sdk use java 23-amzn`.

That said, the same builds also succeeded on `main`. @gunnarmorling What would be the easiest way to observe the failure with Java 22?

**Comment by gunnarmorling** [comment]
The build will always pass; the difference is whether the _META-INF/decodable/stream-names.properties_ gets created or not. To verify, run with Java 23 on main:

    jar -xvf target/custom-pipelines-hello-world-0.1.jar META-INF/decodable/stream-names.properties

The file doesn't exist. Run this with Java 21 on main, or run with Java 23 from this branch, and the file will be extracted from the JAR.

**Comment by gunnarmorling** [comment]
Force-pushed an update which doesn't make any functional difference, but it uses the dedicated Maven compiler plug-in option rather than the generic `<compilerArgs>`.

**Review by nicoweidner — APPROVED** [review]
Thanks, I had totally forgotten that the issue is just with the generated stream names file

**Pull request merged**
